import PropTypes from 'prop-types'
import '../index.css'

export const metadata = {
  title: 'Damian Milczarek',
  description: 'Generated by Next.js',
}


export default function RootLayout({
  children
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}

RootLayout.propTypes = {
  children: PropTypes.node.isRequired,
}
